bank/urls.py
from django.contrib import admin
from django.urls import path, include

from cash import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="home"),
    path('deposite/', views.deposite, name="deposite"),
    path('transfer/', views.transfer, name="transfer"),
    path('transfer_money/', views.transfer_money, name='transfer_money'),
    path('bank/', views.bank, name="bank"),
    path('users/', include('users.urls', namespace='users'))
]


users/urls.py
from django.urls import path

from users.views import login, logout

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout', logout, name='logout'),
]

cash/models.py
from django.db import models

# Create your models here.

class Money(models.Model):
    cardh = models.CharField(max_length=8)
    money = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.cardh
    
    

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from cash.models import Money

# Create your models here.

class User(AbstractUser):
    cardg = models.ForeignKey(to=Money, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.username

cash/forms.py
from django import forms



class Transfer_money(forms.Form):
    cd = forms.CharField(label='' ,widget=forms.TextInput(
        attrs={'class':'input-card', 'placeholder':'Номер счёта'}))
    mn = forms.IntegerField(label='' ,widget=forms.TextInput(
        attrs={'class':'input-money', 'placeholder':'Сумма'}))

users/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django import forms

from users.models import User

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Логин'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Пароль'
    }))

    class Meta:
        model = User
        fields = ['username', 'password']

cash/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.decorators import login_required

from users.models import User
from cash.models import Money

from cash.forms import Transfer_money

# Create your views here.


def index(request):
    context = {'title': 'Банк'}
    return render(request, "cash/index.html", context)

def deposite(request):
    context = {'title':'Deposite'}
    return render(request, "cash/deposite.html", context)

def transfer(request):
    if request.method == 'POST':
        print("POST")
        form = Transfer_money(request.POST)
        if form.is_valid():
            return HttpResponseRedirect('/thanks')
        
    else:
        form = Transfer_money()

    context = {'title':'Transfer', 'form': form}

    return render(request, 'cash/transfer.html', context)



    # return render(request, "cash/transfer.html", context)

@login_required
def bank(request):
    username = request.user.cardg
    # post = Money.objects.filter(card=username).values().first()
    context = {'title':'Bank', 'card': username}
    return render(request, "cash/bank.html", context)

def transfer_money(request):
    if request.method == 'POST':
        print("POST")
        card_ = request.POST.get('cd')
        money_ = request.POST.get('mn')

        cardmyself = request.user.cardg
        # Money.objects.get(cardh=cardmyself).money
        cardmyself = Money.objects.get(cardh=cardmyself)
        cardsend = Money.objects.get(cardh=card_)

        cardmyself.money -= int(money_)
        cardsend.money += int(money_)

        cardmyself.save()
        cardsend.save()
        print("Succesful")

    # return HttpResponseRedirect('/')




    return HttpResponseRedirect(request.META['HTTP_REFERER'])

users/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth
from django.urls import reverse


from users.forms import UserLoginForm

from cash.models import Money

# Create your views here.

def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            print(form.errors)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect('/')
    else:
        form = UserLoginForm()
        print(form.errors)

    context = {'form': form}
    return render(request, 'users/login.html', context)

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/')

cash/templates/cash/bank.html

{% extends 'cash/base.html' %}
{% load static %}

{% block title_block %}{{ title }}{% endblock title_block %}

{% block main %}
<div class="main-container">
    <div class="bk-card-main-container">
        <div class="bk-balance-container">
            <div class="bk-balance-section">
                <div class="bk-balance-section-header">
                    <span>Баланс</span>
                    <div class="visa-image">
                        <img src="https://pluspng.com/img-png/png-visa-visa-icon-1600.png">
                    </div>
                </div>
                <h3>{{ card.money }} USD</h3>
            </div>
        </div>
        <div class="bk-action-container">
            <div class="bk-operation-section">
                <div class="bk-operation-section-header">
                    <span>Операции</span>
                </div>
                <div class="bk-operation-section-main">
                    <a href="{% url 'deposite' %}">Перевести</a>
                    <a href="{% url 'transfer' %}">Пополнить</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock main %}

cash/templates/cash/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}?{% now "U" %}">
    <title>{% block title_block %}{% endblock title_block %}</title>
</head>
<body>
    <header class="header-fixed">
        <div class="header-content">
            <div class="space-between-header">
                <div class="iconbar">
                    <a href="/">
                        <img width="48px" src="{% static 'img/logo.png' %}">
                    </a>
                    <a href="/">Bank</a>
                </div>
                <div class="navbar">
                    <ul class="navbar-list">
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'bank' %}" class="navbar-link">Счёт</a></li>
                        {% endif %}
                        <li><a href="{% url 'deposite' %}" class="navbar-link">Пополнить</a></li>
                        <li><a href="{% url 'transfer' %}" class="navbar-link">Переводы</a></li>
                        {% if not user.is_authenticated %}
                        <li><a href="{% url 'users:login' %}" class="navbar-link">Вход</a></li>
                        {% else %}
                        <li><a href="{% url 'users:logout' %}" class="navbar-link">{{ user.get_username }}</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </header>
    {% block main %}{% endblock main %}
</body>
</html>

cash/templates/cash/deposite.html
{% extends 'cash/base.html' %}
{% load static %}

{% block title_block %}{{ title }}{% endblock title_block %}

{% block main %}
<div class="main-container">
    <input class="input-money" type="tel" placeholder="Номер счёта" size="18"
    maxlength="8" value="{{ cardid.card }}">
    <a class="btn-deposite" href="">Пополнить</a>
</div>
{% endblock main %}

cash/templates/cash/index.html
{% extends 'cash/base.html' %}
{% load static %}

{% block title_block %}{{ title }}{% endblock title_block %}

{% block main %}
<div class="main-container">
    <h1>Сервисы</h1>
    <div class="ind-long-operations-container">
        <a href="" class="ind-long-operations-sections" id="ind-long-section-1">
            <div class="ind-section-item-top">
                <h3>Открыть банковский счёт</h3>
                <span>Легко и удобно: начните свой бизнес прямо сейчас.<br>Откройте счёт 
                    онлайн и начните управлять финансами с легкостью, не покидая дома.</span>
            </div>
            
        </a>
        <a href="{% url 'deposite' %}" class="ind-long-operations-sections" id="ind-long-section-2">
            <div class="ind-section-item-top">
                <h3>Пополнить</h3>
                <span>Пополняйте баланс легко и просто.<br>Наш сервис поможет вам 
                    пополнить счёт в пару кликов, где бы вы ни находились.</span>
            </div>
        </a>
        <a href="{% url 'transfer' %}" class="ind-long-operations-sections" id="ind-long-section-3">
            <div class="ind-section-item-top">
                <h3>Переводы</h3>
                <span>Легко отправляйте деньги в любую точку мира.<br>
                    Наш сервис переводов позволит вам быстро и безопасно 
                    осуществлять финансовые транзакции, делая мир ближе.</span>
            </div>
        </a>
    </div>
    <div class="ind-short-operations-container">
        <div class="ind-short-sections-list">
            <a href="" class="ind-short-sections-link">Счёт</a>
            <a href="" class="ind-short-sections-link">Переводы</a>
            <a href="" class="ind-short-sections-link">Пополнить</a>
        </div>
    </div>
</div>
{% endblock main %}

cash/templates/cash/transfer.html
{% extends 'cash/base.html' %}
{% load static %}

{% block title_block %}{{ title }}{% endblock title_block %}

{% block main %}
<div class="main-container">
    <form action='/transfer_money/' method="post">
        {% csrf_token %}
        {{ form }}
        {% comment %} <input class="input-card" type="tel" placeholder="Номер счёта" size="18"
        maxlength="8"> {% endcomment %}
        {% comment %} <input class="input-money" type="tel" placeholder="Сумма" size="18"
        maxlength="8"> {% endcomment %}
        <input class="btn-deposite" type="submit" value="Перевести">
    </form>
    
</div>
{% endblock main %}

users/templates/users/login.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta name="csrf_token" content="{% csrf_token %}">
	<link href="{% static 'css/login.css' %}" rel="stylesheet"/>
	<title>CodePen - Login </title>
</head>
<body>
	<div class="wrap">
		<form action="{% url 'users:login' %}" method="post">
			{% csrf_token %}
			{% comment %} {{ form.as_p }} {% endcomment %}
			{{ form.username }}
			<div class="bar">
				<i></i>
			</div>
			{{ form.password }}

			<button>Sign in</button>
		</form>
	</div>
	<script src="{% static 'js/login.js' %}"></script>
</body>
</html>